name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-21"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzA4MWY5ZjUtYzkzNy00YzRkLThjYjEtZGVkZjA1MzVmNjI3IiwidGVuYW50X2lkIjoiODMwMGE2ZTk0NzY3NzI0MDhmNWQ1ZGEzZmIzNTk0NThjNjlhZTVlM2M5NTU4NmI3NTNkMjZmMmVmNTMyZmRjZCIsImludGVybmFsX3NlY3JldCI6IjRhNzVjZTgyLTU4ODUtNDYwMi05ODI3LWQwMTQ3MDY2YTE0YyJ9.x9Z2fPe26SZ_84oTV8spt2HjlQLP6CSsZc4o2iT_n-w"
JWT_SECRET = "DFDFDFDDFDFDFDFFODFODJ"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1